kind: pipeline
name: amd64
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: ghcr.io/tystuyfzand/goc:go1.21
    volumes:
      - name: build
        path: /build
    commands:
      - mkdir -p /build
      - goc -o /build/infinitive
    environment:
      CGO_ENABLED: 0
      GOOS: linux,windows,darwin
      GOARCH: 386,amd64,arm,arm64
  - name: publish
    image: plugins/github-release
    volumes:
      - name: build
        path: /build
    settings:
      api_key:
        from_secret: github_api_key
      files: /build/*
    when:
      event: tag
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ghcr.io/tystuyfzand/infinitive
      registry: ghcr.io
      tags:
        - latest
    when:
      event: tag